// flow-typed signature: 51976380f3af7a5af441be49c861bd4d
// flow-typed version: <<STUB>>/@commitlint/config-patternplate_v^4.2.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/config-patternplate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/config-patternplate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@commitlint/config-patternplate/index' {
  declare module.exports: $Exports<'@commitlint/config-patternplate'>;
}
declare module '@commitlint/config-patternplate/index.js' {
  declare module.exports: $Exports<'@commitlint/config-patternplate'>;
}
