// flow-typed signature: 2706296b7f10f1d5d7f80c8f69ddf249
// flow-typed version: <<STUB>>/@commitlint/prompt-cli_v^5.1.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/prompt-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/prompt-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/prompt-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/prompt-cli/cli.js' {
  declare module.exports: $Exports<'@commitlint/prompt-cli/cli'>;
}
