declare module 'axios-debug-log' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
}
// flow-typed signature: 3da4ac803f3104c60a72d07d0897237f
// flow-typed version: <<STUB>>/axios-debug-log_v^0.3.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-debug-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-debug-log/test' {
  declare module.exports: any;
}
declare module 'axios-debug-log/index' {
  declare module.exports: $Exports<'axios-debug-log'>;
}
// Filename aliases
declare module 'axios-debug-log/index.js' {
  declare module.exports: $Exports<'axios-debug-log'>;
}
declare module 'axios-debug-log/test.js' {
  declare module.exports: $Exports<'axios-debug-log/test'>;
}
