// flow-typed signature: ff89d802e01c8b68b3d66b06cb3b229a
// flow-typed version: <<STUB>>/base-64_v^0.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base-64'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'base-64' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base-64/base64' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base-64/base64.js' {
  declare module.exports: $Exports<'base-64/base64'>;
}
