// flow-typed signature: 67d32ca44d304beab89e985386e2fd1a
// flow-typed version: <<STUB>>/eslint-import-resolver-babel-module_vhttps://github.com/blackxored/eslint-import-resolver-babel-module#feat/custom-project-root/flow_v0.60.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-babel-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-babel-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-babel-module/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-babel-module/src/index' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-babel-module/test/examples/components/c1' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-babel-module/test/examples/components/c3' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-babel-module/test/examples/components/sub/envonly/yo' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-babel-module/test/examples/components/sub/sub/c2' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-babel-module/test/examples/file1' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-babel-module/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-babel-module/lib/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/lib/index'>;
}
declare module 'eslint-import-resolver-babel-module/src/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/src/index'>;
}
declare module 'eslint-import-resolver-babel-module/test/examples/components/c1.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/test/examples/components/c1'>;
}
declare module 'eslint-import-resolver-babel-module/test/examples/components/c3.jsx' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/test/examples/components/c3'>;
}
declare module 'eslint-import-resolver-babel-module/test/examples/components/sub/envonly/yo.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/test/examples/components/sub/envonly/yo'>;
}
declare module 'eslint-import-resolver-babel-module/test/examples/components/sub/sub/c2.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/test/examples/components/sub/sub/c2'>;
}
declare module 'eslint-import-resolver-babel-module/test/examples/file1.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/test/examples/file1'>;
}
declare module 'eslint-import-resolver-babel-module/test/index.test.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/test/index.test'>;
}
