// flow-typed signature: 28152d76d92f7f205d3758728452cd46
// flow-typed version: <<STUB>>/graphql-schema-linter_v^0.0.21/flow_v0.60.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-schema-linter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-schema-linter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-schema-linter/lib/cli' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/configuration' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/formatters/f2' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/formatters/json_formatter' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/formatters/text_formatter' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/index' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/inline_configuration' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/defined_types_are_used' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/deprecations_have_a_reason' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/enum_values_all_caps' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/enum_values_have_descriptions' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/enum_values_sorted_alphabetically' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/field_names_are_lower_camelcased' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/fields_have_descriptions' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/index' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/input_object_values_have_descriptions' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/types_are_capitalized' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/types_have_descriptions' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/runner' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/source_map' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-schema-linter/lib/cli.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/cli'>;
}
declare module 'graphql-schema-linter/lib/configuration.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/configuration'>;
}
declare module 'graphql-schema-linter/lib/formatters/f2.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/formatters/f2'>;
}
declare module 'graphql-schema-linter/lib/formatters/json_formatter.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/formatters/json_formatter'>;
}
declare module 'graphql-schema-linter/lib/formatters/text_formatter.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/formatters/text_formatter'>;
}
declare module 'graphql-schema-linter/lib/index.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/index'>;
}
declare module 'graphql-schema-linter/lib/inline_configuration.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/inline_configuration'>;
}
declare module 'graphql-schema-linter/lib/rules/defined_types_are_used.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/defined_types_are_used'>;
}
declare module 'graphql-schema-linter/lib/rules/deprecations_have_a_reason.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/deprecations_have_a_reason'>;
}
declare module 'graphql-schema-linter/lib/rules/enum_values_all_caps.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/enum_values_all_caps'>;
}
declare module 'graphql-schema-linter/lib/rules/enum_values_have_descriptions.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/enum_values_have_descriptions'>;
}
declare module 'graphql-schema-linter/lib/rules/enum_values_sorted_alphabetically.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/enum_values_sorted_alphabetically'>;
}
declare module 'graphql-schema-linter/lib/rules/field_names_are_lower_camelcased.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/field_names_are_lower_camelcased'>;
}
declare module 'graphql-schema-linter/lib/rules/fields_have_descriptions.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/fields_have_descriptions'>;
}
declare module 'graphql-schema-linter/lib/rules/index.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/index'>;
}
declare module 'graphql-schema-linter/lib/rules/input_object_values_have_descriptions.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/input_object_values_have_descriptions'>;
}
declare module 'graphql-schema-linter/lib/rules/types_are_capitalized.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/types_are_capitalized'>;
}
declare module 'graphql-schema-linter/lib/rules/types_have_descriptions.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/types_have_descriptions'>;
}
declare module 'graphql-schema-linter/lib/runner.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/runner'>;
}
declare module 'graphql-schema-linter/lib/source_map.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/source_map'>;
}
declare module 'graphql-schema-linter/lib/validator.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/validator'>;
}
