// flow-typed signature: 2f661329e57ab8d722c44d51c6025ddd
// flow-typed version: <<STUB>>/graphql-server-express_v^1.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-server-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-server-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-server-express/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-server-express/dist/index.js' {
  declare module.exports: $Exports<'graphql-server-express/dist/index'>;
}
