// flow-typed signature: 9d97b99c2ec4ed1f2737a4e7d07333a7
// flow-typed version: <<STUB>>/nubabi-core_v^1.3.1/flow_v0.60.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nubabi-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nubabi-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nubabi-core/app/__tests__/actions.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/app/__tests__/reducer.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/app/actions' {
  declare module.exports: any;
}

declare module 'nubabi-core/app/isClient' {
  declare module.exports: any;
}

declare module 'nubabi-core/app/isReactNative' {
  declare module.exports: any;
}

declare module 'nubabi-core/app/reducer' {
  declare module.exports: any;
}

declare module 'nubabi-core/auth/__tests__/reducer.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/auth/actions' {
  declare module.exports: any;
}

declare module 'nubabi-core/auth/reducer' {
  declare module.exports: any;
}

declare module 'nubabi-core/babies/__tests__/actions.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/babies/__tests__/reducer.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/babies/actions' {
  declare module.exports: any;
}

declare module 'nubabi-core/babies/reducer' {
  declare module.exports: any;
}

declare module 'nubabi-core/components/contextWrapper' {
  declare module.exports: any;
}

declare module 'nubabi-core/components/FelaProvider' {
  declare module.exports: any;
}

declare module 'nubabi-core/components/graphUtils' {
  declare module.exports: any;
}

declare module 'nubabi-core/components/withContext' {
  declare module.exports: any;
}

declare module 'nubabi-core/config/getConfig' {
  declare module.exports: any;
}

declare module 'nubabi-core/config/index' {
  declare module.exports: any;
}

declare module 'nubabi-core/config/reducer' {
  declare module.exports: any;
}

declare module 'nubabi-core/configureApollo' {
  declare module.exports: any;
}

declare module 'nubabi-core/configureDeps' {
  declare module.exports: any;
}

declare module 'nubabi-core/configureEpics' {
  declare module.exports: any;
}

declare module 'nubabi-core/configureFela' {
  declare module.exports: any;
}

declare module 'nubabi-core/configureMiddleware' {
  declare module.exports: any;
}

declare module 'nubabi-core/configureReducer' {
  declare module.exports: any;
}

declare module 'nubabi-core/configureReporting' {
  declare module.exports: any;
}

declare module 'nubabi-core/configureStorage' {
  declare module.exports: any;
}

declare module 'nubabi-core/configureStore' {
  declare module.exports: any;
}

declare module 'nubabi-core/device/reducer' {
  declare module.exports: any;
}

declare module 'nubabi-core/growth/__tests__/reducer.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/growth/reducer' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/__tests__/formatAge.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/__tests__/formatDuration.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/__tests__/formatLikeMessage.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/formatAge' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/formatDate' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/formatDuration' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/formatLikeMessage' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/formatPossessive' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/graphqlUtils' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/measurement' {
  declare module.exports: any;
}

declare module 'nubabi-core/helpers/pluralizeWithSubject' {
  declare module.exports: any;
}

declare module 'nubabi-core/navigation/actions' {
  declare module.exports: any;
}

declare module 'nubabi-core/polyfills/process' {
  declare module.exports: any;
}

declare module 'nubabi-core/settings/__tests__/reducer.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/settings/reducer' {
  declare module.exports: any;
}

declare module 'nubabi-core/themes/defaultTheme' {
  declare module.exports: any;
}

declare module 'nubabi-core/themes/types' {
  declare module.exports: any;
}

declare module 'nubabi-core/themes/typography' {
  declare module.exports: any;
}

declare module 'nubabi-core/types/apolloTypes' {
  declare module.exports: any;
}

declare module 'nubabi-core/types/index' {
  declare module.exports: any;
}

declare module 'nubabi-core/types/modelTypes' {
  declare module.exports: any;
}

declare module 'nubabi-core/types/queryTypes' {
  declare module.exports: any;
}

declare module 'nubabi-core/types/types' {
  declare module.exports: any;
}

declare module 'nubabi-core/ui/__tests__/reducer.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/ui/reducer' {
  declare module.exports: any;
}

declare module 'nubabi-core/viewer/__tests__/reducer.test' {
  declare module.exports: any;
}

declare module 'nubabi-core/viewer/reducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nubabi-core/app/__tests__/actions.test.js' {
  declare module.exports: $Exports<'nubabi-core/app/__tests__/actions.test'>;
}
declare module 'nubabi-core/app/__tests__/reducer.test.js' {
  declare module.exports: $Exports<'nubabi-core/app/__tests__/reducer.test'>;
}
declare module 'nubabi-core/app/actions.js' {
  declare module.exports: $Exports<'nubabi-core/app/actions'>;
}
declare module 'nubabi-core/app/isClient.js' {
  declare module.exports: $Exports<'nubabi-core/app/isClient'>;
}
declare module 'nubabi-core/app/isReactNative.js' {
  declare module.exports: $Exports<'nubabi-core/app/isReactNative'>;
}
declare module 'nubabi-core/app/reducer.js' {
  declare module.exports: $Exports<'nubabi-core/app/reducer'>;
}
declare module 'nubabi-core/auth/__tests__/reducer.test.js' {
  declare module.exports: $Exports<'nubabi-core/auth/__tests__/reducer.test'>;
}
declare module 'nubabi-core/auth/actions.js' {
  declare module.exports: $Exports<'nubabi-core/auth/actions'>;
}
declare module 'nubabi-core/auth/reducer.js' {
  declare module.exports: $Exports<'nubabi-core/auth/reducer'>;
}
declare module 'nubabi-core/babies/__tests__/actions.test.js' {
  declare module.exports: $Exports<'nubabi-core/babies/__tests__/actions.test'>;
}
declare module 'nubabi-core/babies/__tests__/reducer.test.js' {
  declare module.exports: $Exports<'nubabi-core/babies/__tests__/reducer.test'>;
}
declare module 'nubabi-core/babies/actions.js' {
  declare module.exports: $Exports<'nubabi-core/babies/actions'>;
}
declare module 'nubabi-core/babies/reducer.js' {
  declare module.exports: $Exports<'nubabi-core/babies/reducer'>;
}
declare module 'nubabi-core/components/contextWrapper.js' {
  declare module.exports: $Exports<'nubabi-core/components/contextWrapper'>;
}
declare module 'nubabi-core/components/FelaProvider.js' {
  declare module.exports: $Exports<'nubabi-core/components/FelaProvider'>;
}
declare module 'nubabi-core/components/graphUtils.js' {
  declare module.exports: $Exports<'nubabi-core/components/graphUtils'>;
}
declare module 'nubabi-core/components/withContext.js' {
  declare module.exports: $Exports<'nubabi-core/components/withContext'>;
}
declare module 'nubabi-core/config/getConfig.js' {
  declare module.exports: $Exports<'nubabi-core/config/getConfig'>;
}
declare module 'nubabi-core/config/index.js' {
  declare module.exports: $Exports<'nubabi-core/config/index'>;
}
declare module 'nubabi-core/config/reducer.js' {
  declare module.exports: $Exports<'nubabi-core/config/reducer'>;
}
declare module 'nubabi-core/configureApollo.js' {
  declare module.exports: $Exports<'nubabi-core/configureApollo'>;
}
declare module 'nubabi-core/configureDeps.js' {
  declare module.exports: $Exports<'nubabi-core/configureDeps'>;
}
declare module 'nubabi-core/configureEpics.js' {
  declare module.exports: $Exports<'nubabi-core/configureEpics'>;
}
declare module 'nubabi-core/configureFela.js' {
  declare module.exports: $Exports<'nubabi-core/configureFela'>;
}
declare module 'nubabi-core/configureMiddleware.js' {
  declare module.exports: $Exports<'nubabi-core/configureMiddleware'>;
}
declare module 'nubabi-core/configureReducer.js' {
  declare module.exports: $Exports<'nubabi-core/configureReducer'>;
}
declare module 'nubabi-core/configureReporting.js' {
  declare module.exports: $Exports<'nubabi-core/configureReporting'>;
}
declare module 'nubabi-core/configureStorage.js' {
  declare module.exports: $Exports<'nubabi-core/configureStorage'>;
}
declare module 'nubabi-core/configureStore.js' {
  declare module.exports: $Exports<'nubabi-core/configureStore'>;
}
declare module 'nubabi-core/device/reducer.js' {
  declare module.exports: $Exports<'nubabi-core/device/reducer'>;
}
declare module 'nubabi-core/growth/__tests__/reducer.test.js' {
  declare module.exports: $Exports<'nubabi-core/growth/__tests__/reducer.test'>;
}
declare module 'nubabi-core/growth/reducer.js' {
  declare module.exports: $Exports<'nubabi-core/growth/reducer'>;
}
declare module 'nubabi-core/helpers/__tests__/formatAge.test.js' {
  declare module.exports: $Exports<
    'nubabi-core/helpers/__tests__/formatAge.test',
  >;
}
declare module 'nubabi-core/helpers/__tests__/formatDuration.test.js' {
  declare module.exports: $Exports<
    'nubabi-core/helpers/__tests__/formatDuration.test',
  >;
}
declare module 'nubabi-core/helpers/__tests__/formatLikeMessage.test.js' {
  declare module.exports: $Exports<
    'nubabi-core/helpers/__tests__/formatLikeMessage.test',
  >;
}
declare module 'nubabi-core/helpers/formatAge.js' {
  declare module.exports: $Exports<'nubabi-core/helpers/formatAge'>;
}
declare module 'nubabi-core/helpers/formatDate.js' {
  declare module.exports: $Exports<'nubabi-core/helpers/formatDate'>;
}
declare module 'nubabi-core/helpers/formatDuration.js' {
  declare module.exports: $Exports<'nubabi-core/helpers/formatDuration'>;
}
declare module 'nubabi-core/helpers/formatLikeMessage.js' {
  declare module.exports: $Exports<'nubabi-core/helpers/formatLikeMessage'>;
}
declare module 'nubabi-core/helpers/formatPossessive.js' {
  declare module.exports: $Exports<'nubabi-core/helpers/formatPossessive'>;
}
declare module 'nubabi-core/helpers/graphqlUtils.js' {
  declare module.exports: $Exports<'nubabi-core/helpers/graphqlUtils'>;
}
declare module 'nubabi-core/helpers/measurement.js' {
  declare module.exports: $Exports<'nubabi-core/helpers/measurement'>;
}
declare module 'nubabi-core/helpers/pluralizeWithSubject.js' {
  declare module.exports: $Exports<'nubabi-core/helpers/pluralizeWithSubject'>;
}
declare module 'nubabi-core/navigation/actions.js' {
  declare module.exports: $Exports<'nubabi-core/navigation/actions'>;
}
declare module 'nubabi-core/polyfills/process.js' {
  declare module.exports: $Exports<'nubabi-core/polyfills/process'>;
}
declare module 'nubabi-core/settings/__tests__/reducer.test.js' {
  declare module.exports: $Exports<
    'nubabi-core/settings/__tests__/reducer.test',
  >;
}
declare module 'nubabi-core/settings/reducer.js' {
  declare module.exports: $Exports<'nubabi-core/settings/reducer'>;
}
declare module 'nubabi-core/themes/defaultTheme.js' {
  declare module.exports: $Exports<'nubabi-core/themes/defaultTheme'>;
}
declare module 'nubabi-core/themes/types.js' {
  declare module.exports: $Exports<'nubabi-core/themes/types'>;
}
declare module 'nubabi-core/themes/typography.js' {
  declare module.exports: $Exports<'nubabi-core/themes/typography'>;
}
declare module 'nubabi-core/types/apolloTypes.js' {
  declare module.exports: $Exports<'nubabi-core/types/apolloTypes'>;
}
declare module 'nubabi-core/types/index.js' {
  declare module.exports: $Exports<'nubabi-core/types/index'>;
}
declare module 'nubabi-core/types/modelTypes.js' {
  declare module.exports: $Exports<'nubabi-core/types/modelTypes'>;
}
declare module 'nubabi-core/types/queryTypes.js' {
  declare module.exports: $Exports<'nubabi-core/types/queryTypes'>;
}
declare module 'nubabi-core/types/types.js' {
  declare module.exports: $Exports<'nubabi-core/types/types'>;
}
declare module 'nubabi-core/ui/__tests__/reducer.test.js' {
  declare module.exports: $Exports<'nubabi-core/ui/__tests__/reducer.test'>;
}
declare module 'nubabi-core/ui/reducer.js' {
  declare module.exports: $Exports<'nubabi-core/ui/reducer'>;
}
declare module 'nubabi-core/viewer/__tests__/reducer.test.js' {
  declare module.exports: $Exports<'nubabi-core/viewer/__tests__/reducer.test'>;
}
declare module 'nubabi-core/viewer/reducer.js' {
  declare module.exports: $Exports<'nubabi-core/viewer/reducer'>;
}
