// flow-typed signature: 9160f8be624430d3988b26bc59437ff3
// flow-typed version: <<STUB>>/qhistory_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qhistory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qhistory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qhistory/es/index' {
  declare module.exports: any;
}

declare module 'qhistory/lib/index' {
  declare module.exports: any;
}

declare module 'qhistory/umd/qhistory' {
  declare module.exports: any;
}

declare module 'qhistory/umd/qhistory.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qhistory/es/index.js' {
  declare module.exports: $Exports<'qhistory/es/index'>;
}
declare module 'qhistory/lib/index.js' {
  declare module.exports: $Exports<'qhistory/lib/index'>;
}
declare module 'qhistory/umd/qhistory.js' {
  declare module.exports: $Exports<'qhistory/umd/qhistory'>;
}
declare module 'qhistory/umd/qhistory.min.js' {
  declare module.exports: $Exports<'qhistory/umd/qhistory.min'>;
}
