// flow-typed signature: 4b6071863b02391bb49592ff24bf9f07
// flow-typed version: <<STUB>>/react-native-tab-navigator_v^0.3.4/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tab-navigator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tab-navigator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-tab-navigator/Badge' {
  declare module.exports: any;
}

declare module 'react-native-tab-navigator/config/ViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-tab-navigator/Layout' {
  declare module.exports: any;
}

declare module 'react-native-tab-navigator/StaticContainer' {
  declare module.exports: any;
}

declare module 'react-native-tab-navigator/Tab' {
  declare module.exports: any;
}

declare module 'react-native-tab-navigator/TabBar' {
  declare module.exports: any;
}

declare module 'react-native-tab-navigator/TabNavigator' {
  declare module.exports: any;
}

declare module 'react-native-tab-navigator/TabNavigatorItem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-tab-navigator/Badge.js' {
  declare module.exports: $Exports<'react-native-tab-navigator/Badge'>;
}
declare module 'react-native-tab-navigator/config/ViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-tab-navigator/config/ViewPropTypes'>;
}
declare module 'react-native-tab-navigator/Layout.js' {
  declare module.exports: $Exports<'react-native-tab-navigator/Layout'>;
}
declare module 'react-native-tab-navigator/StaticContainer.js' {
  declare module.exports: $Exports<'react-native-tab-navigator/StaticContainer'>;
}
declare module 'react-native-tab-navigator/Tab.js' {
  declare module.exports: $Exports<'react-native-tab-navigator/Tab'>;
}
declare module 'react-native-tab-navigator/TabBar.js' {
  declare module.exports: $Exports<'react-native-tab-navigator/TabBar'>;
}
declare module 'react-native-tab-navigator/TabNavigator.js' {
  declare module.exports: $Exports<'react-native-tab-navigator/TabNavigator'>;
}
declare module 'react-native-tab-navigator/TabNavigatorItem.js' {
  declare module.exports: $Exports<'react-native-tab-navigator/TabNavigatorItem'>;
}
