// flow-typed signature: 99284946e326e086e868a1b6a50acf6c
// flow-typed version: <<STUB>>/react-native-menu_v^0.20.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-menu/src/index' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/index' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeAnimatedOptionsContainer' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenu' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenuContext' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenuOption' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenuOptions' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenuTrigger' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeModel' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-menu/src/index.js' {
  declare module.exports: $Exports<'react-native-menu/src/index'>;
}
declare module 'react-native-menu/src/menu/index.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/index'>;
}
declare module 'react-native-menu/src/menu/makeAnimatedOptionsContainer.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeAnimatedOptionsContainer'>;
}
declare module 'react-native-menu/src/menu/makeMenu.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenu'>;
}
declare module 'react-native-menu/src/menu/makeMenuContext.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenuContext'>;
}
declare module 'react-native-menu/src/menu/makeMenuOption.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenuOption'>;
}
declare module 'react-native-menu/src/menu/makeMenuOptions.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenuOptions'>;
}
declare module 'react-native-menu/src/menu/makeMenuTrigger.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenuTrigger'>;
}
declare module 'react-native-menu/src/menu/makeModel.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeModel'>;
}
declare module 'react-native-menu/src/menu/makeStyles.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeStyles'>;
}
