// flow-typed signature: 0de55233d59cd2e7e10da9ed4d2d630e
// flow-typed version: <<STUB>>/react-native-tab-view_vhttps://github.com/react-native-community/react-native-tab-view#4e1140ef5d15c9d1f146ca138fdc52841d71c3ce/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tab-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tab-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-tab-view/__tests__/TabViewAnimated.test' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/__tests__/TabViewPagerAndroid.test' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/__tests__/TabViewPagerPan.test' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/__tests__/TabViewPagerScroll.test' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/example/main' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/example/src/BottomBarIconTextExample' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/example/src/CoverflowExample' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/example/src/ListViewExample' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/example/src/NoAnimationExample' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/example/src/ScrollViewsExample' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/example/src/TopBarIconExample' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/example/src/TopBarTextExample' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/babel-preset-react-native_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/enzyme-to-json_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-react-native_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/jest_v18.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/PanResponderTypes' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabBar' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewAnimated' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewPagerAndroid' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewPagerPan' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewPagerScroll' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewTransitioner' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewTransitionerTypes' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabViewTypeDefinitions' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TouchableItem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-tab-view/__tests__/TabViewAnimated.test.js' {
  declare module.exports: $Exports<'react-native-tab-view/__tests__/TabViewAnimated.test'>;
}
declare module 'react-native-tab-view/__tests__/TabViewPagerAndroid.test.js' {
  declare module.exports: $Exports<'react-native-tab-view/__tests__/TabViewPagerAndroid.test'>;
}
declare module 'react-native-tab-view/__tests__/TabViewPagerPan.test.js' {
  declare module.exports: $Exports<'react-native-tab-view/__tests__/TabViewPagerPan.test'>;
}
declare module 'react-native-tab-view/__tests__/TabViewPagerScroll.test.js' {
  declare module.exports: $Exports<'react-native-tab-view/__tests__/TabViewPagerScroll.test'>;
}
declare module 'react-native-tab-view/example/main.js' {
  declare module.exports: $Exports<'react-native-tab-view/example/main'>;
}
declare module 'react-native-tab-view/example/src/BottomBarIconTextExample.js' {
  declare module.exports: $Exports<'react-native-tab-view/example/src/BottomBarIconTextExample'>;
}
declare module 'react-native-tab-view/example/src/CoverflowExample.js' {
  declare module.exports: $Exports<'react-native-tab-view/example/src/CoverflowExample'>;
}
declare module 'react-native-tab-view/example/src/ListViewExample.js' {
  declare module.exports: $Exports<'react-native-tab-view/example/src/ListViewExample'>;
}
declare module 'react-native-tab-view/example/src/NoAnimationExample.js' {
  declare module.exports: $Exports<'react-native-tab-view/example/src/NoAnimationExample'>;
}
declare module 'react-native-tab-view/example/src/ScrollViewsExample.js' {
  declare module.exports: $Exports<'react-native-tab-view/example/src/ScrollViewsExample'>;
}
declare module 'react-native-tab-view/example/src/TopBarIconExample.js' {
  declare module.exports: $Exports<'react-native-tab-view/example/src/TopBarIconExample'>;
}
declare module 'react-native-tab-view/example/src/TopBarTextExample.js' {
  declare module.exports: $Exports<'react-native-tab-view/example/src/TopBarTextExample'>;
}
declare module 'react-native-tab-view/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/babel-preset-react-native_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/babel-preset-react-native_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/enzyme-to-json_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/enzyme-to-json_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/eslint-plugin-react-native_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/eslint-plugin-react-native_vx.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/jest_v18.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/jest_v18.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'react-native-tab-view/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-tab-view/flow-typed/npm/react-test-renderer_vx.x.x'>;
}
declare module 'react-native-tab-view/index' {
  declare module.exports: $Exports<'react-native-tab-view'>;
}
declare module 'react-native-tab-view/index.js' {
  declare module.exports: $Exports<'react-native-tab-view'>;
}
declare module 'react-native-tab-view/src/PanResponderTypes.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/PanResponderTypes'>;
}
declare module 'react-native-tab-view/src/TabBar.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabBar'>;
}
declare module 'react-native-tab-view/src/TabViewAnimated.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewAnimated'>;
}
declare module 'react-native-tab-view/src/TabViewPagerAndroid.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewPagerAndroid'>;
}
declare module 'react-native-tab-view/src/TabViewPagerPan.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewPagerPan'>;
}
declare module 'react-native-tab-view/src/TabViewPagerScroll.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewPagerScroll'>;
}
declare module 'react-native-tab-view/src/TabViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewPropTypes'>;
}
declare module 'react-native-tab-view/src/TabViewStyleInterpolator.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewStyleInterpolator'>;
}
declare module 'react-native-tab-view/src/TabViewTransitioner.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewTransitioner'>;
}
declare module 'react-native-tab-view/src/TabViewTransitionerTypes.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewTransitionerTypes'>;
}
declare module 'react-native-tab-view/src/TabViewTypeDefinitions.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabViewTypeDefinitions'>;
}
declare module 'react-native-tab-view/src/TouchableItem.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TouchableItem'>;
}
