// flow-typed signature: 9ebb95cee4a5ad28d9dffb375b348e79
// flow-typed version: <<STUB>>/react-native-dropdownalert_v2.13.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-dropdownalert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-dropdownalert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-dropdownalert/__tests__/DropdownAlert-test' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/DropdownAlert' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/Example/DropdownAlert' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/Example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/Example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-dropdownalert/Example/Main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-dropdownalert/__tests__/DropdownAlert-test.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/__tests__/DropdownAlert-test'>;
}
declare module 'react-native-dropdownalert/DropdownAlert.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/DropdownAlert'>;
}
declare module 'react-native-dropdownalert/Example/DropdownAlert.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/Example/DropdownAlert'>;
}
declare module 'react-native-dropdownalert/Example/index.android.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/Example/index.android'>;
}
declare module 'react-native-dropdownalert/Example/index.ios.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/Example/index.ios'>;
}
declare module 'react-native-dropdownalert/Example/Main.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/Example/Main'>;
}
