// flow-typed signature: 0aa17d4b272087acf43a0e0ed3f585e8
// flow-typed version: <<STUB>>/react-native-floating-label-text-input_v^0.1.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-floating-label-text-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-floating-label-text-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-floating-label-text-input/index' {
  declare module.exports: $Exports<'react-native-floating-label-text-input'>;
}
declare module 'react-native-floating-label-text-input/index.js' {
  declare module.exports: $Exports<'react-native-floating-label-text-input'>;
}
