// flow-typed signature: 414a75bf232898bbe36a1bb4ffb7f9a7
// flow-typed version: <<STUB>>/react-native-simple-markdown_v^1.0.60-rc.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-simple-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-simple-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-simple-markdown/rules' {
  declare module.exports: any;
}

declare module 'react-native-simple-markdown/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-simple-markdown/index' {
  declare module.exports: $Exports<'react-native-simple-markdown'>;
}
declare module 'react-native-simple-markdown/index.js' {
  declare module.exports: $Exports<'react-native-simple-markdown'>;
}
declare module 'react-native-simple-markdown/rules.js' {
  declare module.exports: $Exports<'react-native-simple-markdown/rules'>;
}
declare module 'react-native-simple-markdown/styles.js' {
  declare module.exports: $Exports<'react-native-simple-markdown/styles'>;
}
