// flow-typed signature: 5d3aec22b98d2c4df14aca3b576c5ad7
// flow-typed version: <<STUB>>/react-native-menu_v^0.23.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-menu/src/index' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/index' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeAnimatedOptionsContainer' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenu' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenuContext' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenuOption' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenuOptions' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeMenuTrigger' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeModel' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/makeStyles' {
  declare module.exports: any;
}

declare module 'react-native-menu/src/menu/MenuContext.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-menu/src/index.js' {
  declare module.exports: $Exports<'react-native-menu/src/index'>;
}
declare module 'react-native-menu/src/menu/index.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/index'>;
}
declare module 'react-native-menu/src/menu/makeAnimatedOptionsContainer.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeAnimatedOptionsContainer'>;
}
declare module 'react-native-menu/src/menu/makeMenu.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenu'>;
}
declare module 'react-native-menu/src/menu/makeMenuContext.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenuContext'>;
}
declare module 'react-native-menu/src/menu/makeMenuOption.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenuOption'>;
}
declare module 'react-native-menu/src/menu/makeMenuOptions.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenuOptions'>;
}
declare module 'react-native-menu/src/menu/makeMenuTrigger.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeMenuTrigger'>;
}
declare module 'react-native-menu/src/menu/makeModel.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeModel'>;
}
declare module 'react-native-menu/src/menu/makeStyles.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/makeStyles'>;
}
declare module 'react-native-menu/src/menu/MenuContext.test.js' {
  declare module.exports: $Exports<'react-native-menu/src/menu/MenuContext.test'>;
}
