// flow-typed signature: 66adc5ace47e326845d4ab9af29f6716
// flow-typed version: <<STUB>>/react-native-video-player_v^0.8.5/flow_v0.60.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-video-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-video-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'react-native-video-player/index' {
  declare module.exports: $Exports<'react-native-video-player'>;
}
declare module 'react-native-video-player/index.js' {
  declare module.exports: $Exports<'react-native-video-player'>;
}
