// flow-typed signature: 860d5cc072313fa32e85de1c8dfe7b98
// flow-typed version: <<STUB>>/react-native-audio_v^3.2.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-audio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-audio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'react-native-audio/index' {
  declare module.exports: $Exports<'react-native-audio'>;
}
declare module 'react-native-audio/index.js' {
  declare module.exports: $Exports<'react-native-audio'>;
}
