// flow-typed signature: f8742712d23ed7dcaf1f8031b9f95c91
// flow-typed version: <<STUB>>/react-native-autogrow-textinput_vhttps://github.com/jackdcrawford/react-native-autogrow-textinput#0fd7e7f2/flow_v0.60.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-autogrow-textinput'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-autogrow-textinput' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-autogrow-textinput/example/app' {
  declare module.exports: any;
}

declare module 'react-native-autogrow-textinput/example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-autogrow-textinput/example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-autogrow-textinput/src/AutoGrowingTextInput' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-autogrow-textinput/example/app.js' {
  declare module.exports: $Exports<
    'react-native-autogrow-textinput/example/app',
  >;
}
declare module 'react-native-autogrow-textinput/example/index.android.js' {
  declare module.exports: $Exports<
    'react-native-autogrow-textinput/example/index.android',
  >;
}
declare module 'react-native-autogrow-textinput/example/index.ios.js' {
  declare module.exports: $Exports<
    'react-native-autogrow-textinput/example/index.ios',
  >;
}
declare module 'react-native-autogrow-textinput/index' {
  declare module.exports: $Exports<'react-native-autogrow-textinput'>;
}
declare module 'react-native-autogrow-textinput/index.js' {
  declare module.exports: $Exports<'react-native-autogrow-textinput'>;
}
declare module 'react-native-autogrow-textinput/src/AutoGrowingTextInput.js' {
  declare module.exports: $Exports<
    'react-native-autogrow-textinput/src/AutoGrowingTextInput',
  >;
}
