// flow-typed signature: 69efaf3b361d3431ec0eefe17ee9e194
// flow-typed version: <<STUB>>/react-native-cached-image_v^1.3.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-cached-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-cached-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-cached-image/CachedImage' {
  declare module.exports: any;
}

declare module 'react-native-cached-image/ImageCacheProvider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-cached-image/CachedImage.js' {
  declare module.exports: $Exports<'react-native-cached-image/CachedImage'>;
}
declare module 'react-native-cached-image/ImageCacheProvider.js' {
  declare module.exports: $Exports<'react-native-cached-image/ImageCacheProvider'>;
}
declare module 'react-native-cached-image/index' {
  declare module.exports: $Exports<'react-native-cached-image'>;
}
declare module 'react-native-cached-image/index.js' {
  declare module.exports: $Exports<'react-native-cached-image'>;
}
