// flow-typed signature: c162d778ebc971fd736f4a97444ce8d0
// flow-typed version: <<STUB>>/react-native-photo-browser_v^0.3.1/flow_v0.60.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-photo-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-photo-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-photo-browser/lib/bar/BarContainer' {
  declare module.exports: any;
}

declare module 'react-native-photo-browser/lib/bar/BottomBar' {
  declare module.exports: any;
}

declare module 'react-native-photo-browser/lib/bar/index' {
  declare module.exports: any;
}

declare module 'react-native-photo-browser/lib/bar/TopBar' {
  declare module.exports: any;
}

declare module 'react-native-photo-browser/lib/constants' {
  declare module.exports: any;
}

declare module 'react-native-photo-browser/lib/FullScreenContainer' {
  declare module.exports: any;
}

declare module 'react-native-photo-browser/lib/GridContainer' {
  declare module.exports: any;
}

declare module 'react-native-photo-browser/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-photo-browser/lib/media/index' {
  declare module.exports: any;
}

declare module 'react-native-photo-browser/lib/media/Photo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-photo-browser/lib/bar/BarContainer.js' {
  declare module.exports: $Exports<
    'react-native-photo-browser/lib/bar/BarContainer',
  >;
}
declare module 'react-native-photo-browser/lib/bar/BottomBar.js' {
  declare module.exports: $Exports<
    'react-native-photo-browser/lib/bar/BottomBar',
  >;
}
declare module 'react-native-photo-browser/lib/bar/index.js' {
  declare module.exports: $Exports<'react-native-photo-browser/lib/bar/index'>;
}
declare module 'react-native-photo-browser/lib/bar/TopBar.js' {
  declare module.exports: $Exports<'react-native-photo-browser/lib/bar/TopBar'>;
}
declare module 'react-native-photo-browser/lib/constants.js' {
  declare module.exports: $Exports<'react-native-photo-browser/lib/constants'>;
}
declare module 'react-native-photo-browser/lib/FullScreenContainer.js' {
  declare module.exports: $Exports<
    'react-native-photo-browser/lib/FullScreenContainer',
  >;
}
declare module 'react-native-photo-browser/lib/GridContainer.js' {
  declare module.exports: $Exports<
    'react-native-photo-browser/lib/GridContainer',
  >;
}
declare module 'react-native-photo-browser/lib/index.js' {
  declare module.exports: $Exports<'react-native-photo-browser/lib/index'>;
}
declare module 'react-native-photo-browser/lib/media/index.js' {
  declare module.exports: $Exports<
    'react-native-photo-browser/lib/media/index',
  >;
}
declare module 'react-native-photo-browser/lib/media/Photo.js' {
  declare module.exports: $Exports<
    'react-native-photo-browser/lib/media/Photo',
  >;
}
