// flow-typed signature: 82867d6871e79d5b264f775c122bb448
// flow-typed version: <<STUB>>/react-native-video-thumbnail_v^1.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-video-thumbnail'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-video-thumbnail' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-video-thumbnail/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-video-thumbnail/index.ios.js' {
  declare module.exports: $Exports<'react-native-video-thumbnail/index.ios'>;
}
