declare module 'react-native-snap-carousel' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

  // Filename aliases
}
// flow-typed signature: 61678034c27eff14d9dccc308da7285b
// flow-typed version: <<STUB>>/react-native-snap-carousel_v^2.1.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-snap-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-snap-carousel/index' {
  declare module.exports: $Exports<'react-native-snap-carousel'>;
}
declare module 'react-native-snap-carousel/index.js' {
  declare module.exports: $Exports<'react-native-snap-carousel'>;
}
