// flow-typed signature: c869434da846ad73e97f3c6120d1309c
// flow-typed version: <<STUB>>/react-native-contacts-wrapper_v^0.2.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-contacts-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-contacts-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-contacts-wrapper/index' {
  declare module.exports: $Exports<'react-native-contacts-wrapper'>;
}
declare module 'react-native-contacts-wrapper/index.js' {
  declare module.exports: $Exports<'react-native-contacts-wrapper'>;
}
