// flow-typed signature: 082c8620fff6998336329021bdba8404
// flow-typed version: <<STUB>>/react-native-spinkit_v^1.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-spinkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-spinkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-spinkit/scripts/rnpm-prelink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-spinkit/index' {
  declare module.exports: $Exports<'react-native-spinkit'>;
}
declare module 'react-native-spinkit/index.js' {
  declare module.exports: $Exports<'react-native-spinkit'>;
}
declare module 'react-native-spinkit/scripts/rnpm-prelink.js' {
  declare module.exports: $Exports<'react-native-spinkit/scripts/rnpm-prelink'>;
}
