// flow-typed signature: ffe84237e59c2b559aec4e6b46966ebe
// flow-typed version: <<STUB>>/react-native-simple-markdown_vhttps://github.com/blackxored/react-native-simple-markdown#fix/add-keys/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-simple-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-simple-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-simple-markdown/rules' {
  declare module.exports: any;
}

declare module 'react-native-simple-markdown/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-simple-markdown/index' {
  declare module.exports: $Exports<'react-native-simple-markdown'>;
}
declare module 'react-native-simple-markdown/index.js' {
  declare module.exports: $Exports<'react-native-simple-markdown'>;
}
declare module 'react-native-simple-markdown/rules.js' {
  declare module.exports: $Exports<'react-native-simple-markdown/rules'>;
}
declare module 'react-native-simple-markdown/styles.js' {
  declare module.exports: $Exports<'react-native-simple-markdown/styles'>;
}
