declare module 'react-native-dropdownalert' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
}
// flow-typed signature: b7a7355a4d5a2270d63c2bad5fe8f89f
// flow-typed version: <<STUB>>/react-native-dropdownalert_v^2.7.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-dropdownalert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-dropdownalert/DropdownAlert' {
  declare module.exports: any;
}
// Filename aliases
declare module 'react-native-dropdownalert/DropdownAlert.js' {
  declare module.exports: $Exports<'react-native-dropdownalert/DropdownAlert'>;
}
