// flow-typed signature: 270be6dc1ed56f1d7da461cc28a6e175
// flow-typed version: <<STUB>>/redux-injector_v^0.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-injector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-injector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-injector/lib/ReduxInjector' {
  declare module.exports: any;
}

declare module 'redux-injector/src/ReduxInjector' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-injector/lib/ReduxInjector.js' {
  declare module.exports: $Exports<'redux-injector/lib/ReduxInjector'>;
}
declare module 'redux-injector/src/ReduxInjector.js' {
  declare module.exports: $Exports<'redux-injector/src/ReduxInjector'>;
}
