// flow-typed signature: b2a8ebe50e86db45dff36d0518315693
// flow-typed version: <<STUB>>/string_v^3.3.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string/dist/string' {
  declare module.exports: any;
}

declare module 'string/dist/string.min' {
  declare module.exports: any;
}

declare module 'string/gulpfile' {
  declare module.exports: any;
}

declare module 'string/lib/_count' {
  declare module.exports: any;
}

declare module 'string/lib/_splitLeft' {
  declare module.exports: any;
}

declare module 'string/lib/_splitRight' {
  declare module.exports: any;
}

declare module 'string/lib/string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string/dist/string.js' {
  declare module.exports: $Exports<'string/dist/string'>;
}
declare module 'string/dist/string.min.js' {
  declare module.exports: $Exports<'string/dist/string.min'>;
}
declare module 'string/gulpfile.js' {
  declare module.exports: $Exports<'string/gulpfile'>;
}
declare module 'string/lib/_count.js' {
  declare module.exports: $Exports<'string/lib/_count'>;
}
declare module 'string/lib/_splitLeft.js' {
  declare module.exports: $Exports<'string/lib/_splitLeft'>;
}
declare module 'string/lib/_splitRight.js' {
  declare module.exports: $Exports<'string/lib/_splitRight'>;
}
declare module 'string/lib/string.js' {
  declare module.exports: $Exports<'string/lib/string'>;
}
