// flow-typed signature: 56e761eb9142f59e944f9e2747430cf8
// flow-typed version: <<STUB>>/victory-chart_vhttps://github.com/blackxored/victory-chart#fix/victory-group-dates/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'victory-chart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'victory-chart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'victory-chart/demo/app' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/animation-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/bubble-data' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/create-container-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/debug-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/events-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/group-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/selection-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/symbol-data' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-area-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-axis-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-bar-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-brush-container-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-candlestick-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-chart-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-cursor-container-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-errorbar-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-line-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-polar-chart-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-scatter-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-tooltip-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-voronoi-container-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-voronoi-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/components/victory-zoom-container-demo' {
  declare module.exports: any;
}

declare module 'victory-chart/demo/theme/victory-axis-differential-styling-theme' {
  declare module.exports: any;
}

declare module 'victory-chart/dist/victory-chart' {
  declare module.exports: any;
}

declare module 'victory-chart/dist/victory-chart.min' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/brush-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/create-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/cursor-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/selection-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-brush-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-cursor-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-selection-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-voronoi-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-zoom-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/voronoi-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/zoom-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-area/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-area/victory-area' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-axis/victory-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-bar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-bar/victory-bar' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-candlestick/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-candlestick/victory-candlestick' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-chart/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-chart/victory-chart' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-errorbar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-errorbar/victory-errorbar' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-group/victory-group' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-line/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-line/victory-line' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-polar-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-polar-axis/victory-polar-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-scatter/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-scatter/victory-scatter' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-stack/victory-stack' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-voronoi/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-voronoi/victory-voronoi' {
  declare module.exports: any;
}

declare module 'victory-chart/es/helpers/axis' {
  declare module.exports: any;
}

declare module 'victory-chart/es/helpers/common-props' {
  declare module.exports: any;
}

declare module 'victory-chart/es/helpers/event-handlers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/helpers/wrapper' {
  declare module.exports: any;
}

declare module 'victory-chart/es/index' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/brush-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/create-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/cursor-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/selection-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-brush-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-cursor-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-selection-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-voronoi-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-zoom-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/voronoi-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/zoom-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-area/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-area/victory-area' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-axis/victory-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-bar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-bar/victory-bar' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-candlestick/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-candlestick/victory-candlestick' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-chart/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-chart/victory-chart' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-errorbar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-errorbar/victory-errorbar' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-group/victory-group' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-line/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-line/victory-line' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-polar-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-polar-axis/victory-polar-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-scatter/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-scatter/victory-scatter' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-stack/victory-stack' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-voronoi/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-voronoi/victory-voronoi' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/helpers/axis' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/helpers/common-props' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/helpers/event-handlers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/helpers/wrapper' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/index' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-area/sample-data' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-area/victory-area.bench' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-axis/sample-data' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-axis/victory-axis.bench' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-bar/sample-data' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-bar/victory-bar.bench' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-candlestick/sample-data' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-candlestick/victory-candlestick.bench' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-errorbar/sample-data' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-errorbar/victory-errorbar.bench' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-line/sample-data' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-line/victory-line.bench' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-scatter/sample-data' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-scatter/victory-scatter.bench' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-voronoi/sample-data' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/components/victory-voronoi/victory-voronoi.bench' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/helpers/bench-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/bench/helpers/sample-data-generator' {
  declare module.exports: any;
}

declare module 'victory-chart/perf/client/main' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/brush-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/create-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/cursor-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/selection-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-brush-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-cursor-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-selection-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-voronoi-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-zoom-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/voronoi-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/zoom-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-area/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-area/victory-area' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-axis/victory-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-bar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-bar/victory-bar' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-candlestick/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-candlestick/victory-candlestick' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-chart/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-chart/victory-chart' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-errorbar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-errorbar/victory-errorbar' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-group/victory-group' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-line/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-line/victory-line' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-polar-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-polar-axis/victory-polar-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-scatter/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-scatter/victory-scatter' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-stack/victory-stack' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-voronoi/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-voronoi/victory-voronoi' {
  declare module.exports: any;
}

declare module 'victory-chart/src/helpers/axis' {
  declare module.exports: any;
}

declare module 'victory-chart/src/helpers/common-props' {
  declare module.exports: any;
}

declare module 'victory-chart/src/helpers/event-handlers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/helpers/wrapper' {
  declare module.exports: any;
}

declare module 'victory-chart/src/index' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/main' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-area/helper-methods.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-area/victory-area.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-axis/helper-methods.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-axis/victory-axis.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-bar/victory-bar.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-candlestick/helper-methods.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-candlestick/victory-candlestick.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-chart/helper-methods.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-chart/victory-chart.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-errorbars/victory-errorbars.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-line/victory-line.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-scatter/helper-methods.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-scatter/victory-scatter.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-voronoi/victory-voronoi.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-wrappers/victory-group.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/components/victory-wrappers/victory-stack.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/helpers/axis.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/client/spec/helpers/wrapper.spec' {
  declare module.exports: any;
}

declare module 'victory-chart/test/svg-test-helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'victory-chart/demo/app.js' {
  declare module.exports: $Exports<'victory-chart/demo/app'>;
}
declare module 'victory-chart/demo/components/animation-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/animation-demo'>;
}
declare module 'victory-chart/demo/components/bubble-data.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/bubble-data'>;
}
declare module 'victory-chart/demo/components/create-container-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/create-container-demo'>;
}
declare module 'victory-chart/demo/components/debug-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/debug-demo'>;
}
declare module 'victory-chart/demo/components/events-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/events-demo'>;
}
declare module 'victory-chart/demo/components/group-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/group-demo'>;
}
declare module 'victory-chart/demo/components/selection-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/selection-demo'>;
}
declare module 'victory-chart/demo/components/symbol-data.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/symbol-data'>;
}
declare module 'victory-chart/demo/components/victory-area-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-area-demo'>;
}
declare module 'victory-chart/demo/components/victory-axis-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-axis-demo'>;
}
declare module 'victory-chart/demo/components/victory-bar-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-bar-demo'>;
}
declare module 'victory-chart/demo/components/victory-brush-container-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-brush-container-demo'>;
}
declare module 'victory-chart/demo/components/victory-candlestick-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-candlestick-demo'>;
}
declare module 'victory-chart/demo/components/victory-chart-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-chart-demo'>;
}
declare module 'victory-chart/demo/components/victory-cursor-container-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-cursor-container-demo'>;
}
declare module 'victory-chart/demo/components/victory-errorbar-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-errorbar-demo'>;
}
declare module 'victory-chart/demo/components/victory-line-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-line-demo'>;
}
declare module 'victory-chart/demo/components/victory-polar-chart-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-polar-chart-demo'>;
}
declare module 'victory-chart/demo/components/victory-scatter-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-scatter-demo'>;
}
declare module 'victory-chart/demo/components/victory-tooltip-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-tooltip-demo'>;
}
declare module 'victory-chart/demo/components/victory-voronoi-container-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-voronoi-container-demo'>;
}
declare module 'victory-chart/demo/components/victory-voronoi-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-voronoi-demo'>;
}
declare module 'victory-chart/demo/components/victory-zoom-container-demo.js' {
  declare module.exports: $Exports<'victory-chart/demo/components/victory-zoom-container-demo'>;
}
declare module 'victory-chart/demo/theme/victory-axis-differential-styling-theme.js' {
  declare module.exports: $Exports<'victory-chart/demo/theme/victory-axis-differential-styling-theme'>;
}
declare module 'victory-chart/dist/victory-chart.js' {
  declare module.exports: $Exports<'victory-chart/dist/victory-chart'>;
}
declare module 'victory-chart/dist/victory-chart.min.js' {
  declare module.exports: $Exports<'victory-chart/dist/victory-chart.min'>;
}
declare module 'victory-chart/es/components/containers/brush-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/brush-helpers'>;
}
declare module 'victory-chart/es/components/containers/create-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/create-container'>;
}
declare module 'victory-chart/es/components/containers/cursor-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/cursor-helpers'>;
}
declare module 'victory-chart/es/components/containers/selection-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/selection-helpers'>;
}
declare module 'victory-chart/es/components/containers/victory-brush-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-brush-container'>;
}
declare module 'victory-chart/es/components/containers/victory-cursor-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-cursor-container'>;
}
declare module 'victory-chart/es/components/containers/victory-selection-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-selection-container'>;
}
declare module 'victory-chart/es/components/containers/victory-voronoi-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-voronoi-container'>;
}
declare module 'victory-chart/es/components/containers/victory-zoom-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-zoom-container'>;
}
declare module 'victory-chart/es/components/containers/voronoi-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/voronoi-helpers'>;
}
declare module 'victory-chart/es/components/containers/zoom-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/zoom-helpers'>;
}
declare module 'victory-chart/es/components/victory-area/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-area/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-area/victory-area.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-area/victory-area'>;
}
declare module 'victory-chart/es/components/victory-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-axis/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-axis/victory-axis.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-axis/victory-axis'>;
}
declare module 'victory-chart/es/components/victory-bar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-bar/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-bar/victory-bar.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-bar/victory-bar'>;
}
declare module 'victory-chart/es/components/victory-candlestick/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-candlestick/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-candlestick/victory-candlestick.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-candlestick/victory-candlestick'>;
}
declare module 'victory-chart/es/components/victory-chart/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-chart/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-chart/victory-chart.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-chart/victory-chart'>;
}
declare module 'victory-chart/es/components/victory-errorbar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-errorbar/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-errorbar/victory-errorbar.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-errorbar/victory-errorbar'>;
}
declare module 'victory-chart/es/components/victory-group/victory-group.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-group/victory-group'>;
}
declare module 'victory-chart/es/components/victory-line/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-line/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-line/victory-line.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-line/victory-line'>;
}
declare module 'victory-chart/es/components/victory-polar-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-polar-axis/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-polar-axis/victory-polar-axis.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-polar-axis/victory-polar-axis'>;
}
declare module 'victory-chart/es/components/victory-scatter/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-scatter/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-scatter/victory-scatter.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-scatter/victory-scatter'>;
}
declare module 'victory-chart/es/components/victory-stack/victory-stack.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-stack/victory-stack'>;
}
declare module 'victory-chart/es/components/victory-voronoi/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-voronoi/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-voronoi/victory-voronoi.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-voronoi/victory-voronoi'>;
}
declare module 'victory-chart/es/helpers/axis.js' {
  declare module.exports: $Exports<'victory-chart/es/helpers/axis'>;
}
declare module 'victory-chart/es/helpers/common-props.js' {
  declare module.exports: $Exports<'victory-chart/es/helpers/common-props'>;
}
declare module 'victory-chart/es/helpers/event-handlers.js' {
  declare module.exports: $Exports<'victory-chart/es/helpers/event-handlers'>;
}
declare module 'victory-chart/es/helpers/wrapper.js' {
  declare module.exports: $Exports<'victory-chart/es/helpers/wrapper'>;
}
declare module 'victory-chart/es/index.js' {
  declare module.exports: $Exports<'victory-chart/es/index'>;
}
declare module 'victory-chart/lib/components/containers/brush-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/brush-helpers'>;
}
declare module 'victory-chart/lib/components/containers/create-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/create-container'>;
}
declare module 'victory-chart/lib/components/containers/cursor-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/cursor-helpers'>;
}
declare module 'victory-chart/lib/components/containers/selection-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/selection-helpers'>;
}
declare module 'victory-chart/lib/components/containers/victory-brush-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-brush-container'>;
}
declare module 'victory-chart/lib/components/containers/victory-cursor-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-cursor-container'>;
}
declare module 'victory-chart/lib/components/containers/victory-selection-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-selection-container'>;
}
declare module 'victory-chart/lib/components/containers/victory-voronoi-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-voronoi-container'>;
}
declare module 'victory-chart/lib/components/containers/victory-zoom-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-zoom-container'>;
}
declare module 'victory-chart/lib/components/containers/voronoi-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/voronoi-helpers'>;
}
declare module 'victory-chart/lib/components/containers/zoom-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/zoom-helpers'>;
}
declare module 'victory-chart/lib/components/victory-area/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-area/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-area/victory-area.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-area/victory-area'>;
}
declare module 'victory-chart/lib/components/victory-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-axis/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-axis/victory-axis.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-axis/victory-axis'>;
}
declare module 'victory-chart/lib/components/victory-bar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-bar/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-bar/victory-bar.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-bar/victory-bar'>;
}
declare module 'victory-chart/lib/components/victory-candlestick/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-candlestick/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-candlestick/victory-candlestick.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-candlestick/victory-candlestick'>;
}
declare module 'victory-chart/lib/components/victory-chart/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-chart/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-chart/victory-chart.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-chart/victory-chart'>;
}
declare module 'victory-chart/lib/components/victory-errorbar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-errorbar/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-errorbar/victory-errorbar.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-errorbar/victory-errorbar'>;
}
declare module 'victory-chart/lib/components/victory-group/victory-group.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-group/victory-group'>;
}
declare module 'victory-chart/lib/components/victory-line/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-line/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-line/victory-line.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-line/victory-line'>;
}
declare module 'victory-chart/lib/components/victory-polar-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-polar-axis/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-polar-axis/victory-polar-axis.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-polar-axis/victory-polar-axis'>;
}
declare module 'victory-chart/lib/components/victory-scatter/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-scatter/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-scatter/victory-scatter.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-scatter/victory-scatter'>;
}
declare module 'victory-chart/lib/components/victory-stack/victory-stack.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-stack/victory-stack'>;
}
declare module 'victory-chart/lib/components/victory-voronoi/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-voronoi/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-voronoi/victory-voronoi.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-voronoi/victory-voronoi'>;
}
declare module 'victory-chart/lib/helpers/axis.js' {
  declare module.exports: $Exports<'victory-chart/lib/helpers/axis'>;
}
declare module 'victory-chart/lib/helpers/common-props.js' {
  declare module.exports: $Exports<'victory-chart/lib/helpers/common-props'>;
}
declare module 'victory-chart/lib/helpers/event-handlers.js' {
  declare module.exports: $Exports<'victory-chart/lib/helpers/event-handlers'>;
}
declare module 'victory-chart/lib/helpers/wrapper.js' {
  declare module.exports: $Exports<'victory-chart/lib/helpers/wrapper'>;
}
declare module 'victory-chart/lib/index.js' {
  declare module.exports: $Exports<'victory-chart/lib/index'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-area/sample-data.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-area/sample-data'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-area/victory-area.bench.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-area/victory-area.bench'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-axis/sample-data.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-axis/sample-data'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-axis/victory-axis.bench.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-axis/victory-axis.bench'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-bar/sample-data.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-bar/sample-data'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-bar/victory-bar.bench.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-bar/victory-bar.bench'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-candlestick/sample-data.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-candlestick/sample-data'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-candlestick/victory-candlestick.bench.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-candlestick/victory-candlestick.bench'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-errorbar/sample-data.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-errorbar/sample-data'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-errorbar/victory-errorbar.bench.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-errorbar/victory-errorbar.bench'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-line/sample-data.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-line/sample-data'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-line/victory-line.bench.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-line/victory-line.bench'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-scatter/sample-data.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-scatter/sample-data'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-scatter/victory-scatter.bench.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-scatter/victory-scatter.bench'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-voronoi/sample-data.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-voronoi/sample-data'>;
}
declare module 'victory-chart/perf/client/bench/components/victory-voronoi/victory-voronoi.bench.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/components/victory-voronoi/victory-voronoi.bench'>;
}
declare module 'victory-chart/perf/client/bench/helpers/bench-helpers.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/helpers/bench-helpers'>;
}
declare module 'victory-chart/perf/client/bench/helpers/sample-data-generator.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/bench/helpers/sample-data-generator'>;
}
declare module 'victory-chart/perf/client/main.js' {
  declare module.exports: $Exports<'victory-chart/perf/client/main'>;
}
declare module 'victory-chart/src/components/containers/brush-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/brush-helpers'>;
}
declare module 'victory-chart/src/components/containers/create-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/create-container'>;
}
declare module 'victory-chart/src/components/containers/cursor-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/cursor-helpers'>;
}
declare module 'victory-chart/src/components/containers/selection-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/selection-helpers'>;
}
declare module 'victory-chart/src/components/containers/victory-brush-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-brush-container'>;
}
declare module 'victory-chart/src/components/containers/victory-cursor-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-cursor-container'>;
}
declare module 'victory-chart/src/components/containers/victory-selection-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-selection-container'>;
}
declare module 'victory-chart/src/components/containers/victory-voronoi-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-voronoi-container'>;
}
declare module 'victory-chart/src/components/containers/victory-zoom-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-zoom-container'>;
}
declare module 'victory-chart/src/components/containers/voronoi-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/voronoi-helpers'>;
}
declare module 'victory-chart/src/components/containers/zoom-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/zoom-helpers'>;
}
declare module 'victory-chart/src/components/victory-area/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-area/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-area/victory-area.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-area/victory-area'>;
}
declare module 'victory-chart/src/components/victory-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-axis/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-axis/victory-axis.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-axis/victory-axis'>;
}
declare module 'victory-chart/src/components/victory-bar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-bar/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-bar/victory-bar.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-bar/victory-bar'>;
}
declare module 'victory-chart/src/components/victory-candlestick/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-candlestick/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-candlestick/victory-candlestick.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-candlestick/victory-candlestick'>;
}
declare module 'victory-chart/src/components/victory-chart/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-chart/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-chart/victory-chart.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-chart/victory-chart'>;
}
declare module 'victory-chart/src/components/victory-errorbar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-errorbar/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-errorbar/victory-errorbar.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-errorbar/victory-errorbar'>;
}
declare module 'victory-chart/src/components/victory-group/victory-group.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-group/victory-group'>;
}
declare module 'victory-chart/src/components/victory-line/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-line/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-line/victory-line.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-line/victory-line'>;
}
declare module 'victory-chart/src/components/victory-polar-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-polar-axis/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-polar-axis/victory-polar-axis.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-polar-axis/victory-polar-axis'>;
}
declare module 'victory-chart/src/components/victory-scatter/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-scatter/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-scatter/victory-scatter.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-scatter/victory-scatter'>;
}
declare module 'victory-chart/src/components/victory-stack/victory-stack.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-stack/victory-stack'>;
}
declare module 'victory-chart/src/components/victory-voronoi/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-voronoi/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-voronoi/victory-voronoi.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-voronoi/victory-voronoi'>;
}
declare module 'victory-chart/src/helpers/axis.js' {
  declare module.exports: $Exports<'victory-chart/src/helpers/axis'>;
}
declare module 'victory-chart/src/helpers/common-props.js' {
  declare module.exports: $Exports<'victory-chart/src/helpers/common-props'>;
}
declare module 'victory-chart/src/helpers/event-handlers.js' {
  declare module.exports: $Exports<'victory-chart/src/helpers/event-handlers'>;
}
declare module 'victory-chart/src/helpers/wrapper.js' {
  declare module.exports: $Exports<'victory-chart/src/helpers/wrapper'>;
}
declare module 'victory-chart/src/index.js' {
  declare module.exports: $Exports<'victory-chart/src/index'>;
}
declare module 'victory-chart/test/client/main.js' {
  declare module.exports: $Exports<'victory-chart/test/client/main'>;
}
declare module 'victory-chart/test/client/spec/components/victory-area/helper-methods.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-area/helper-methods.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-area/victory-area.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-area/victory-area.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-axis/helper-methods.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-axis/helper-methods.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-axis/victory-axis.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-axis/victory-axis.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-bar/victory-bar.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-bar/victory-bar.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-candlestick/helper-methods.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-candlestick/helper-methods.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-candlestick/victory-candlestick.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-candlestick/victory-candlestick.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-chart/helper-methods.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-chart/helper-methods.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-chart/victory-chart.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-chart/victory-chart.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-errorbars/victory-errorbars.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-errorbars/victory-errorbars.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-line/victory-line.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-line/victory-line.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-scatter/helper-methods.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-scatter/helper-methods.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-scatter/victory-scatter.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-scatter/victory-scatter.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-voronoi/victory-voronoi.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-voronoi/victory-voronoi.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-wrappers/victory-group.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-wrappers/victory-group.spec'>;
}
declare module 'victory-chart/test/client/spec/components/victory-wrappers/victory-stack.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/components/victory-wrappers/victory-stack.spec'>;
}
declare module 'victory-chart/test/client/spec/helpers/axis.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/helpers/axis.spec'>;
}
declare module 'victory-chart/test/client/spec/helpers/wrapper.spec.js' {
  declare module.exports: $Exports<'victory-chart/test/client/spec/helpers/wrapper.spec'>;
}
declare module 'victory-chart/test/svg-test-helper.js' {
  declare module.exports: $Exports<'victory-chart/test/svg-test-helper'>;
}
