# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'NuBabiMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NuBabiMobile
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod "FBSDKCoreKit";
  pod "FBSDKLoginKit";
  pod "FBSDKShareKit";
  pod "react-native-fbsdk", :path => '../platforms/native/node_modules/react-native-fbsdk/ios'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
	pod 'React', :path => '../node_modules/react-native', :subspecs => [
		'BatchedBridge', # Required For React Native 0.45.0+
		'Core',
		# Add any other subspecs you want to use in your project
  ]

  target 'NuBabiMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NuBabiMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NuBabiMobile-tvOS

  target 'NuBabiMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
