# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NuBabiMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NuBabiMobile
  pod 'Firebase/Core'

  target 'NuBabiMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NuBabiMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NuBabiMobile-tvOS

  target 'NuBabiMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
