
image: node:latest

before_script:
 — npm prune
 — npm install
 — npm install -g firebase-tools firebase-bolt grunt-cli

stages:
  - deploy

cache:
  paths:
    — node_modules/
  key: “$CI_BUILD_REPO”

deploy_to_firebase:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - grunt all
    - firebase-bolt rules.bolt
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY