#!/usr/bin/env sh
FLOW_VERSION=0.60.1
FLOW_OPTIONS="-f $FLOW_VERSION install --overwrite"
echo "\nInstalling defs for root...\n"
flow-typed install

echo "\nInstalling defs for core...\n"
cd core && flow-typed $FLOW_OPTIONS && cd ..

echo "\nInstalling defs for native...\n"
cd platforms/native && flow-typed $FLOW_OPTIONS && cd ../../

echo "\nInstalling defs for graphql-utils...\n"
cd libs/graphql-utils && flow-typed $FLOW_OPTIONS && cd ../../

echo "\nInstalling defs for server...\n"
cd platforms/server/graphql && flow-typed $FLOW_OPTIONS && cd ../../../

echo "\nInstalling defs for web...\n"
cd platforms/web && flow-typed $FLOW_OPTIONS && cd ../../
